spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update

clerk.issuer=https://helped-parakeet-71.clerk.accounts.dev
clerk.jwks-url=https://helped-parakeet-71.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clipdrop.apiKey=${CLIPDROP_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}

server.port=${PORT:8080}